version: '3.4'

services:
   sourcingdb:
      container_name: sourcingdb
      restart: always
      volumes:
         - ${WEBAPP_STORAGE_HOME}/site:/data/db
       #- ./data:/data/db
      ports:
         - "27017:27017"
   
   esourcing.products:   
      container_name: esourcingproducts
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ProductDatabaseSettings:ConnectionSetting=mongodb://sourcingdb:27017" #appsetting.json daki bilgileri buraya da ekledik.
      depends_on:
           - sourcingdb
      ports:
        - "8000:80"
      volumes:
        - ${HOME}/.microsoft/.usersecrets/:/roor/.microsoft/usersecrets
        - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

